export enum ConfigurationSettingsType {
  GWP = "GWP",
  PROJECTIONS_WITH_MEASURES = "PROJECTIONS_WITH_MEASURES",
  PROJECTIONS_WITH_ADDITIONAL_MEASURES = "PROJECTIONS_WITH_ADDITIONAL_MEASURES",
  PROJECTIONS_WITHOUT_MEASURES = "PROJECTIONS_WITHOUT_MEASURES",
  ANNEX_II_REPORT_CATEGORIES = "ANNEX_II_REPORT_CATEGORIES",
  SECTOR_YEAR_CONFIGURATION = "SECTOR_YEAR_CONFIGURATION",
}
